project:
  type: website
  output-dir: docs

website:
  title: "BIOS 600: Intro to Probability and Statistical Inference"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



